package src.Ex05_Inheritance;

public abstract class Shape {
	//variables
	
	private String name;
	private String colour;
	private double x;
	private double y;
	
	//constructor

	/**
	 * @param name
	 * @param colour
	 * @param x
	 * @param y
	 */
	public Shape(String name, String colour, double x, double y) {
		super();
		this.name = name;
		this.colour = colour;
		this.x = x;
		this.y = y;
	}


	//getters and setters
	public String getName() {
		return name;
	}



	public void setName(String name) {
		this.name = name;
	}



	public String getColour() {
		return colour;
	}



	public void setColour(String colour) {
		this.colour = colour;
	}



	public double getX() {
		return x;
	}



	public void setX(double x) {
		this.x = x;
	}



	public double getY() {
		return y;
	}



	public void setY(double y) {
		this.y = y;
	}



	@Override
	public String toString() {
		return "Shape [name=" + name + ", colour=" + colour + ", x=" + x + ", y=" + y + "]";
	}
	
	//abstract methods - implementation (body) gets generated by subclasses
	public abstract double getArea();
	
	public abstract Point getCentrePoint();

}
